# Generated by Django 3.2.24 on 2024-05-26 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog_profile', '0003_alter_dogprofile_dog_age'),
        ('posts', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dog_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dog_profile.dogprofile'),
        ),
    ]
