# Generated by Django 3.2.24 on 2024-05-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogprofile',
            name='at_rescue',
            field=models.BooleanField(default=False),
        ),
    ]
