# Generated by Django 3.2.25 on 2024-04-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenderChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SizeChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StatusChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='dog_gender',
            field=models.IntegerField(choices=[(0, 'TBC'), (1, 'Male'), (2, 'Female')], default=0),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='dog_size',
            field=models.IntegerField(choices=[(0, 'TBC'), (1, 'Small'), (2, 'Large')], default=0),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='status',
            field=models.IntegerField(choices=[(0, 'To arrive'), (1, 'Not available'), (2, 'Available'), (3, 'Rehomed')], default=0),
        ),
    ]
