# Generated by Django 3.2.25 on 2024-04-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogprofile',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='rehomed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
