# Generated by Django 3.2.25 on 2024-04-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_profile', '0002_auto_20240416_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogprofile',
            name='vaccine_canine_hepatitis',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='vaccine_canine_parvovirus',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='vaccine_distemper',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='vaccine_kennelcough',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='vaccine_leptospirosis',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='vaccine_puppy_first',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='vaccine_puppy_second',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='vaccine_rabies',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='vaccine_sixmonthboost',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='vaccine_twelvemonthboost',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
