# Generated by Django 3.2.24 on 2024-05-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_profile', '0002_alter_dogprofile_at_rescue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogprofile',
            name='dog_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
