# Generated by Django 3.2.24 on 2024-04-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog_profile', '0003_auto_20240416_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogprofile',
            name='vaccine_canine_hepatitis',
        ),
        migrations.RemoveField(
            model_name='dogprofile',
            name='vaccine_canine_parvovirus',
        ),
        migrations.RemoveField(
            model_name='dogprofile',
            name='vaccine_distemper',
        ),
        migrations.RemoveField(
            model_name='dogprofile',
            name='vaccine_kennelcough',
        ),
        migrations.RemoveField(
            model_name='dogprofile',
            name='vaccine_leptospirosis',
        ),
        migrations.RemoveField(
            model_name='dogprofile',
            name='vaccine_puppy_first',
        ),
        migrations.RemoveField(
            model_name='dogprofile',
            name='vaccine_puppy_second',
        ),
        migrations.RemoveField(
            model_name='dogprofile',
            name='vaccine_rabies',
        ),
        migrations.RemoveField(
            model_name='dogprofile',
            name='vaccine_sixmonthboost',
        ),
        migrations.RemoveField(
            model_name='dogprofile',
            name='vaccine_twelvemonthboost',
        ),
    ]
