# Generated by Django 3.2.24 on 2024-04-18 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dog_profile', '0004_auto_20240418_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogVaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overdue', models.BooleanField(default=True)),
                ('vaccine_canine_parvovirus', models.DateTimeField(blank=True, null=True)),
                ('vaccine_canine_hepatitis', models.DateTimeField(blank=True, null=True)),
                ('vaccine_distemper', models.DateTimeField(blank=True, null=True)),
                ('vaccine_leptospirosis', models.DateTimeField(blank=True, null=True)),
                ('vaccine_kennelcough', models.DateTimeField(blank=True, null=True)),
                ('vaccine_rabies', models.DateTimeField(blank=True, null=True)),
                ('vaccine_puppy_first', models.DateTimeField(blank=True, null=True)),
                ('vaccine_puppy_second', models.DateTimeField(blank=True, null=True)),
                ('vaccine_sixmonthboost', models.DateTimeField(blank=True, null=True)),
                ('vaccine_twelvemonthboost', models.DateTimeField(blank=True, null=True)),
                ('dog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog_profile.dogprofile')),
            ],
            options={
                'ordering': ['-dog_id'],
            },
        ),
    ]
