# Generated by Django 3.2.25 on 2024-04-17 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog_profile', '0003_auto_20240416_1634'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favourite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='dog_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited', to='dog_profile.dogprofile'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL),
        ),
    ]
